### ISSUE TITLE
ATD AMANDA Backlog — Unisys

### ISSUE THREAD

**Issue by TracyLinder** [cityofaustin/atd-amanda#11]
Work on the [ATD AMANDA Backlog](https://github.com/cityofaustin/atd-data-tech/issues/432) delivered by Unisys. 

- [x] Sync w/ Stacey Wuest regarding proper process for this engagement 
- [x] Sync w/ Peggy from finance 
- [x] Add this to CMGB portfolio
- [x] Send documentation to Unisys; requesting estimate
- [x] Sync w/ Peggy on estimate; get finance approval for estimate & work
- [x] Request spending authority from CMGB

*Migrated to [atd-data-tech #1515](https://github.com/cityofaustin/atd-data-tech/issues/1515)*

**Comment by johnclary** [comment]
@TracyLinder would you update Ryan W with the latest on this? He didn't seem to know this was in progress.

**Comment by TracyLinder** [comment]
@johnclary I gave him an update at the audit meeting earlier today.

**Comment by johnclary** [comment]
@TracyLinder pinging you to make sure this is moving forward. do you need help?
